[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd ai_search/ai_runner && python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8001"
GOOGLE_API_KEY = "${{secrets.GOOGLE_API_KEY}}"
